
<div>
    <form>
        <div class="form-group" id="leiturapcpu">
            <label class="control-label" for="inputIcon">Leitura Tempo PCPU01:</label>
            <div class="input-group">
                <div class="input-group-addon"><i class="glyphicon glyphicon-time"></i></div>
                <input id="tempo01" name="tempo01" type="time" style="width: 10%;"  class="input form-control" required title="Digite o tempo que a unidade permaneceu parada." x-moz-errormessage="Não se esqueça  do tempo..." >
                <button type="submit" class="btn btn-success">Adicionar</button>
            </div>
        </div>
         <div class="form-group" id="leiturapcpu">
            <label class="control-label" for="inputIcon">Leitura Tempo PCPU02:</label>
            <div class="input-group">
                <div class="input-group-addon"><i class="glyphicon glyphicon-time"></i></div>
                <input id="tempo01" name="tempo01" type="time" style="width: 10%;"  class="input form-control" required title="Digite o tempo que a unidade permaneceu parada." x-moz-errormessage="Não se esqueça  do tempo..." >
                <button type="submit" class="btn btn-success">Adicionar</button>
            </div>
        </div>
         <div class="form-group" id="leiturapcpu">
            <label class="control-label" for="inputIcon">Leitura Tempo PCPU03:</label>
            <div class="input-group">
                <div class="input-group-addon"><i class="glyphicon glyphicon-time"></i></div>
                <input id="tempo03" name="tempo03" type="time" style="width: 10%;"  class="input form-control" required title="Digite o tempo que a unidade permaneceu parada." x-moz-errormessage="Não se esqueça  do tempo..." >
                <button type="submit" class="btn btn-success">Adicionar</button>
            </div>
        </div>
    </form>
</div>